on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Download Go Modules
      run: go mod download

    - name: Run Test
      run: go test -v ./...

  build_go_executables:
  # Build go executables and store them as artifacts
    runs-on: ubuntu-latest
    needs: test-go
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Download Go Modules
      run: go mod download

    - name: Create the ~/artifacts directory if it doesn't exist
      run: mkdir -p ~/artifacts

    - name: Build NSE downloader tools
      run: go build -o ~/artifacts ./cmd/nse_downloader

    - name: Build NSE downloader tool for windows
      run: GOOS=windows go build -o ~/artifacts ./cmd/nse_downloader

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: excecutables
        path: ~/artifacts

  deploy-to-lambda:
  # Build go executables and store them as artifacts
    runs-on: ubuntu-latest

    needs: build_go_executables

    environment: aws_lambda_deployment

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Download Go modules
      run: go mod download

    - name: Install nodejs
      uses: actions/setup-node@v4
      with:
          node-version: '21'

    - name: Install serverless
      run: npm install -g serverless

    - name: Check SLS version
      run: sls --version

    - name: Deploy to Lambda
      run: make deploy

    - name: Cleanup
      run: sls remove
